### ISSUE TITLE
[BUG] indexes on namespaced nodes can not be displayed

### ISSUE THREAD

**Issue by SnowMakerDemo** [eXist-db/monex#122]
![image](https://user-images.githubusercontent.com/28621460/78452093-e0298200-76bb-11ea-8caa-932a4878d647.png)
![image](https://user-images.githubusercontent.com/28621460/78452101-e7e92680-76bb-11ea-81af-d944769d4364.png)
![image](https://user-images.githubusercontent.com/28621460/78452108-ecadda80-76bb-11ea-82be-d0de83a178a5.png)

**Context (please always complete the following information):**
 - win 10 
 - eXist-db version: [e.g. 5.2.0]
 - Java Version [e.g. Java8u121]

**Additional context**
- How is eXist-db installed? [e.g. JAR installer]
- Any custom changes in e.g. `conf.xml`? 
no

**Comment by duncdrum** [comment]
i suspect and error with the empty namespace being reset, based on the fragment posted by the OP. But we do need a full sample to reproduce. We should consider adding a test, as this kind of namespace resetting is easily triggered.

**Comment by joewiz** [comment]
@SnowMakerDemo The cause of the error is that the `@qname` value in the following range index entry is invalid:

```xml
<create qname="xs:schema/@appinfo:test" type="xs:string"/>
```

The clearest description of how to use `qname` is in the documentation for the old range index: https://exist-db.org/exist/apps/doc/oldrangeindex#pathvsqname and @wolfgangmm's original article describing the feature: http://atomic.exist-db.org/blogs/eXist/NewIndexing. 

Basically, `@qname` is meant to create a *context-independent* range index: you specify only an element name or an attribute name. So `qname="xs:schema` and `qname="@appinfo:test"` are fine, but `qname="xs:schema/@appinfo:test"` and `qname="//inproceedings/author"` are invalid. 

I will see if I can get our collection.xconf.xsd schema to raise an error when a "/" character is used in `@qname`.

That said, the way monex handles errors could be improved. Maybe we should validate the xconf file before trying to display index contents. Or we could catch errors in the display of index contents and simply suggest opening the xconf in eXide so that a schema check can be run.
